### ISSUE TITLE
Obtenir les informations sur les musiques (metadonnées)

### ISSUE THREAD

**Issue by nsobczak** [nsobczak/Audio-Player-Application#11]

**Comment by bLandais** [comment]
Est-ce vraiment pour l'activité 2 qu'il faut faire ça ?

**Exemple :** 

Supposons qu'une personne déplace des fichiers MP3 dans son téléphone.
Lors du lancement de l'application, on arrive sur l'activité 1.
L'activité va lister tous les fichiers présents dans le dossier concerné, faire un delta avec sa base de données locale, et mettre à jour les informations si nécessaire.
S'il y a de nouvelles musiques, l'application va compléter les métadonnées (éventuellement manquantes) de la piste et les ajouter dans la BDD.

Après c'est vrai qu'on pourrait faire ca dans l'activité 2, mais le souci c'est que si on a besoin d'une info dans l'activité 1 on est bloqué ! :wink:

**Comment by nsobczak** [comment]
Justement comme je me demandais je voulais le mettre dans les 2. Tu penses que c'est que dans l'activité 1 qu'on récupère tout et on passe le bundle à l'activité 2 ?

**Comment by bLandais** [comment]
A première vue, je dirais que oui.... à voir avec les autres
