### ISSUE TITLE
Activité 1 :

### ISSUE THREAD

**Issue by nsobczak** [nsobczak/Audio-Player-Application#4]
Version fonctionnelle de l'activité principale
- liste des chansons

**Comment by bLandais** [comment]
@QLev @hongchangxu 

~~Comme convenu avec le mail de @Paullecodeur59, il est **indispensable** que vous décidiez d'une sous-tâche parmi l'activité 1 afin d'avancer dessus et de préparer la réunion du 2 Mars. Avez-vous déjà choisi / avancé ?~~
@nsobczak  et moi avons déjà codé : 
- Les différents fragments ( #12 ) + Récupérer les musiques du téléphone ( #5 : en cours ) 
- Appel vers l'API pour les musiques ( #11 ) + BDD (en cours)

~~On a besoin d'un retour rapide s'il vous plait sur les tâches que vous prenez. Merci de nous informer le plus vite possible.~~

**Comment by bLandais** [comment]
@Paullecodeur59 

@QLev a choisi la tâche #9 ~~, il ne reste donc plus qu'à @hongchangxu de choisir~~
@hongchangxu a choisi la tâche #6 

~~@hongchangxu Merci de bien vouloir choisir avant _demain soir_ pour qu'on puisse s'organiser sur l'activité. La réunion d'Android aura lieue le _2 Mars_ : il faut donc avoir avancé sur nos tâches respectives d'ici-là. Hong chang, j'attends ta réponse s'il te plait (tu peux aussi l'envoyer à @Paullecodeur59 ou @nsobczak ) sur la tâche que tu souhaites. [La liste est visible ici](https://github.com/nsobczak/Audio-Player-Application/issues?q=is%3Aissue+is%3Aopen+label%3Aactivit%C3%A9_01)~~
